### ISSUE TITLE
Error 500: player without achievements

### ISSUE THREAD

**Issue by muchnameless** [Senither/hypixel-skyblock-facade#4]
encountered the following error 500 when requesting a player with no achievements:
(uuid to recreate: 3ecec3fa7a024a4c95317448cff0a6cc)

```
{
  "status": 500,
  "reason": "Cannot read property 'skyblock_excavator' of undefined",
  "stack": [
    "TypeError: Cannot read property 'skyblock_excavator' of undefined",
    "    at Object.parseHypixelPlayer (/root/hypixel-skyblock-facade/build/utils/Hypixel.js:55:34)",
    "    at /root/hypixel-skyblock-facade/build/routes/v1/GetProfiles.js:7:28",
    "    at runMicrotasks (<anonymous>)",
    "    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
  ]
}
```

**Comment by Senither** [comment]
Should be fixed now, thanks for reporting the bug. 👍
