### ISSUE TITLE
Cannot read property 'experience' of undefined

### ISSUE THREAD

**Issue by dukio** [Senither/hypixel-skyblock-facade#6]
Url: `https://hypixel-api.senither.com/v1/profiles/781b200ae40543daa5038559f5947953/weight?key=<KEY>
`

Player: https://sky.shiiyu.moe/stats/simiboo/Orange

```json
{
  "status": 500,
  "reason": "Cannot read property 'experience' of undefined",
  "stack": [
    "TypeError: Cannot read property 'experience' of undefined",
    "    at DungeonsGenerator.generateClassProperties (/root/hypixel-skyblock-facade/build/generators/DungeonsGenerator.js:176:40)",
    "    at DungeonsGenerator.build (/root/hypixel-skyblock-facade/build/generators/DungeonsGenerator.js:53:28)",
    "    at Object.parseSkyBlockProfiles (/root/hypixel-skyblock-facade/build/utils/Hypixel.js:100:51)",
    "    at /root/hypixel-skyblock-facade/build/routes/v1/GetProfileWithStrategy.js:9:30",
    "    at runMicrotasks (<anonymous>)",
    "    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
  ]
}
```

I think the issue might arise when a player is missing a dungeon class in the hypixel api response (he's missing tank):
![image](https://user-images.githubusercontent.com/2744227/116259410-10840880-a776-11eb-8e5c-39b9a898d494.png)

**Comment by Senither** [comment]
You were right on point!
Thanks for reporting the bug, it should be fixed now 👍
